<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Roberto.local" name="Test" tests="2" failures="1" timestamp="2 Sep 2021 06:10:47 GMT" time="16.07" errors="0">
  <testcase name="signUp" time="1.185" classname="com.test.seleniumTest.SeleniumTest"/>
  <testcase name="test2" time="0.003" classname="com.test.seleniumTest.SeleniumTest">
    <failure type="java.lang.AssertionError" message="numbers don&amp;apos;t add up expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: numbers don't add up expected [2] but found [1]
	at com.test.seleniumTest.SeleniumTest.test2(SeleniumTest.java:62)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
